@echo off
echo Starting D-CRYPT Shield Engines...

echo Starting Databases...
start cmd /k "docker-compose up -d"

echo Waiting 15 seconds for Neo4j and Postgres to fully boot up...
powershell -command "Start-Sleep -Seconds 15"

echo Starting Main API...
start cmd /k "cd backend-core && go run cmd/server/main.go"

echo Starting Python ML Service...
start cmd /k "cd intelligence-service && .\.venv\Scripts\python.exe native_server.py"

echo Starting Live Tracker...
start cmd /k "cd backend-core && go run cmd/tracker/main.go"

echo Starting Next.js Frontend...
start cmd /k "cd frontend-dashboard && npm run dev"

echo Securing Localtunnel Connection...
start cmd /k "npx -y localtunnel --port 9090 --subdomain dcrypt-api-sih"

echo All systems GO! You can close this window.
