"use client";

import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import {
  ShieldIcon,
  CheckCircleIcon,
  CopyIcon,
  DownloadIcon,
  NetworkIcon,
  ActivityIcon,
} from "@/components/Icons";

function VerifyNoticeContent() {
  const searchParams = useSearchParams();

  const rawHash = searchParams.get("hash") || "3a8f9c1b7e4d2a6f8b0e1d3c5a7f9b2d4e6a8c0f1b3d5e7a9c2b4d6e8f0a1b2c";
  const caseId = searchParams.get("case") || "CASE-2024-IN-0891";

  const [copied, setCopied] = useState(false);

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const isDemoCase2 = caseId.includes("4402") || caseId.includes("002");
  const isDemoCase3 = caseId.includes("7719") || caseId.includes("003");

  const caseDetails = isDemoCase2
    ? {
        firNumber: "FIR No. 89/2024 / Cyber Crime Division, CID",
        policeStation: "Cyber Crime Division, CID Karnataka, Bengaluru",
        crimeCategory: "Bridge Exploitation, OFAC Sanctions & Mixer Laundering",
        suspectWallet: "0x098B716B8Aaf215190988513afF39BA65EdAB176",
        chain: "Ethereum Mainnet (EVM)",
        attributedVasp: "Tornado Cash Smart Contracts / Stargate Tron Bridge",
        volume: "100.0000 ETH (INR 2,26,80,000)",
        riskScore: "99.8 / 100 (CRITICAL)",
      }
    : isDemoCase3
    ? {
        firNumber: "FIR No. 277/2024 / Cyberabad Cyber Crime PS",
        policeStation: "Cyber Crime Police Station, Cyberabad, Telangana",
        crimeCategory: "Telegram Task Investment Scam & P2P Mule Structuring",
        suspectWallet: "0x8c7C313Bf280e816a7f9a2D8f1a1A711b7dF46c8",
        chain: "Ethereum Mainnet (EVM)",
        attributedVasp: "Binance India Institutional Gateway (FIU-IND/CAS/2024/0089)",
        volume: "45,000.00 USDT (INR 37,80,000)",
        riskScore: "91.5 / 100 (HIGH RISK)",
      }
    : {
        firNumber: "FIR No. 412/2024 / Cyber PS Special Cell",
        policeStation: "Cyber Crime Police Station, Special Cell, New Delhi",
        crimeCategory: "Cyber Extortion, Digital Lending Fraud & Organized Laundering",
        suspectWallet: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
        chain: "Ethereum Mainnet (EVM)",
        attributedVasp: "CoinDCX India (Neblio Technologies Pvt Ltd / FIU-IND/CAS/2023/0014)",
        volume: "14.2500 ETH (INR 32,31,900)",
        riskScore: "89.2 / 100 (HIGH RISK)",
      };

  const pdfUrl = `http://localhost:9090/api/v1/report/${caseId}`;

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans antialiased selection:bg-blue-100 selection:text-blue-900">
      {/* Header Bar */}
      <header className="w-full bg-white border-b border-slate-200 px-6 lg:px-12 py-3.5 flex items-center justify-between sticky top-0 z-20 shadow-xs">
        <Link href="/" className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center shadow-md shadow-blue-500/20">
            <ShieldIcon size={18} />
          </div>
          <div>
            <span className="font-extrabold tracking-tight text-base text-slate-900 flex items-center gap-2">
              D-CRYPT <span className="text-blue-600">SHIELD</span>
            </span>
            <p className="text-[9px] font-semibold text-slate-500 tracking-wider uppercase">
              Forensic Verification Portal
            </p>
          </div>
        </Link>

        <div className="flex items-center gap-3">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs font-bold font-mono">
            <CheckCircleIcon size={14} className="text-emerald-600" />
            SEAL VERIFIED
          </span>
          <Link
            href="/"
            className="text-xs font-bold text-slate-600 hover:text-slate-900 px-3 py-1.5 rounded-lg border border-slate-300 bg-white hover:bg-slate-50 transition-colors"
          >
            Return to Home
          </Link>
        </div>
      </header>

      {/* Main Container */}
      <main className="max-w-4xl mx-auto px-6 py-10">
        {/* Prototype Disclaimer Banner */}
        <div className="mb-6 p-3 bg-amber-50 border border-amber-200 rounded-xl text-amber-900 text-xs flex items-center gap-3">
          <span className="px-2 py-0.5 rounded bg-amber-200 text-amber-900 font-extrabold text-[10px] tracking-wide uppercase shrink-0">
            PROTOTYPE NOTICE
          </span>
          <p className="leading-relaxed">
            This verification certificate was generated by the <strong>D-CRYPT SHIELD Prototype Forensics Engine</strong> for technical demonstration and court exhibit evaluation.
          </p>
        </div>

        {/* Verification Certificate Card */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-xl overflow-hidden mb-8">
          {/* Top Banner */}
          <div className="bg-slate-900 text-white p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center justify-between gap-6 border-b border-slate-800">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 text-[11px] font-mono font-bold uppercase tracking-wider">
                  NIST FIPS 180-4 CRYPTOGRAPHIC SEAL VALIDATED
                </span>
              </div>
              <h1 className="text-2xl sm:text-3xl font-black tracking-tight text-white">
                Statutory Evidence Certificate
              </h1>
              <p className="text-slate-400 text-xs mt-1">
                Section 63 Bharatiya Sakshya Adhiniyam, 2023 / Section 65B Indian Evidence Act
              </p>
            </div>

            <div className="shrink-0">
              <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 border-2 border-emerald-500/40 text-emerald-400 flex items-center justify-center shadow-lg shadow-emerald-500/10">
                <CheckCircleIcon size={36} />
              </div>
            </div>
          </div>

          {/* Hash Seal Section */}
          <div className="p-6 sm:p-8 border-b border-slate-200 bg-slate-50/50">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-2">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-600 font-mono">
                CANONICAL EVIDENCE INTEGRITY SEAL (SHA-256):
              </span>
              <button
                onClick={() => copyToClipboard(rawHash)}
                className="inline-flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 cursor-pointer"
              >
                <CopyIcon size={14} />
                {copied ? "Copied Hash!" : "Copy SHA-256 Seal"}
              </button>
            </div>

            <div className="p-4 bg-white rounded-xl border border-slate-300 font-mono text-xs text-blue-900 break-all leading-relaxed shadow-xs">
              {rawHash}
            </div>

            <p className="text-[11px] text-slate-500 mt-2">
              Digest computed across the raw canonical on-chain transaction hops and suspect profile prior to PDF compilation. Immune to post-generation tampering.
            </p>
          </div>

          {/* Case Matrix Table */}
          <div className="p-6 sm:p-8 space-y-6">
            <h3 className="text-sm font-black uppercase tracking-wider text-slate-800 font-mono">
              Attested Case Forensics Record
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Case Reference ID
                </span>
                <span className="font-mono font-bold text-slate-900 text-sm">
                  {caseId}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  FIR Registration
                </span>
                <span className="font-semibold text-slate-800">
                  {caseDetails.firNumber}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Police Station / Unit
                </span>
                <span className="font-semibold text-slate-800">
                  {caseDetails.policeStation}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Crime Classification
                </span>
                <span className="font-semibold text-slate-800">
                  {caseDetails.crimeCategory}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Suspect Unhosted Wallet
                </span>
                <span className="font-mono font-bold text-rose-700 break-all">
                  {caseDetails.suspectWallet}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Attributed VASP Off-Ramp
                </span>
                <span className="font-semibold text-blue-700">
                  {caseDetails.attributedVasp}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Traced Volume (Fiat Eq.)
                </span>
                <span className="font-bold text-emerald-700 text-sm">
                  {caseDetails.volume}
                </span>
              </div>

              <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500 block mb-1">
                  Forensic Risk Score
                </span>
                <span className="font-bold text-rose-600 text-sm">
                  {caseDetails.riskScore}
                </span>
              </div>
            </div>

            {/* Verification Command Helper */}
            <div className="p-4 bg-slate-900 rounded-xl text-slate-300 font-mono text-xs">
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] text-slate-400 font-bold uppercase">
                  Verify Offline in Windows PowerShell / Command Prompt:
                </span>
                <button
                  onClick={() => copyToClipboard(`certutil -hashfile Section91_Requisition_${caseId}.pdf SHA256`)}
                  className="text-[11px] text-blue-400 hover:text-blue-300"
                >
                  Copy Command
                </button>
              </div>
              <code className="text-emerald-400 block bg-slate-950 p-2.5 rounded border border-slate-800 select-all">
                certutil -hashfile Section91_Requisition_{caseId}.pdf SHA256
              </code>
            </div>

            {/* Action Buttons */}
            <div className="pt-4 flex flex-wrap items-center gap-3">
              <a
                href={pdfUrl}
                target="_blank"
                rel="noreferrer"
                className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs px-5 py-3 rounded-lg shadow-md shadow-blue-600/20 transition-all"
              >
                <DownloadIcon size={16} />
                Download Court-Admissible PDF
              </a>

              <Link
                href={`/case/${caseId}`}
                className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs px-4 py-3 rounded-lg transition-all"
              >
                <NetworkIcon size={16} />
                Inspect in Case Terminal
              </Link>

              <Link
                href="/"
                className="flex items-center gap-2 bg-white hover:bg-slate-50 border border-slate-300 text-slate-700 font-bold text-xs px-4 py-3 rounded-lg transition-all"
              >
                <ActivityIcon size={16} />
                Landing Page Showcase
              </Link>
            </div>

          </div>
        </div>

        {/* Footer Note */}
        <div className="text-center text-xs text-slate-500 space-y-1">
          <p>D-CRYPT SHIELD • Blockchain Forensics & VASP Attribution Protocol</p>
          <p className="text-[11px] text-slate-400">Section 91 CrPC • Section 102 BNSS • Section 63 BSA 2023</p>
        </div>
      </main>
    </div>
  );
}

export default function VerifyNoticePage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-slate-50 flex items-center justify-center text-slate-600 font-mono text-sm">
          Loading forensic verification record...
        </div>
      }
    >
      <VerifyNoticeContent />
    </Suspense>
  );
}
