package handlers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
	"github.com/go-pdf/fpdf"
)

type ReportResponse struct {
	Success     bool   `json:"success"`
	Filename    string `json:"filename"`
	Sha256Hash  string `json:"sha256_hash"`
	GeneratedAt string `json:"generated_at"`
	DownloadURL string `json:"download_url"`
}

// GenerateReport generates a PDF trace report.
func (h *Handler) GenerateReport(c *gin.Context) {
	caseID := c.Param("case_id")
	ctx := c.Request.Context()

	var suspectAddress string
	var riskScore float64
	var confScore float64

	// Demo case mock lookup
	if caseID == "demo-case-001" { suspectAddress = "0x098B716B8Aaf215190988513afF39BA65EdAB176"; riskScore = 99.9; confScore = 99.0 } else
	if caseID == "demo-case-002" { suspectAddress = "0x8c7C313Bf280e816a7f9a2D8f1a1A711b7dF46c8"; riskScore = 88.5; confScore = 92.5 } else
	if caseID == "demo-case-003" { suspectAddress = "0x5c43B1eD97e52d009611D89b74fA829FE4ac56b1"; riskScore = 15.0; confScore = 98.0 } else
	if caseID == "demo-case-004" { suspectAddress = "0x71660c4005BA85c37ccec55d0C4493E66Fe775d3"; riskScore = 22.0; confScore = 98.0 } else {
		// Real lookup
		result, err := h.repo.GetCase(ctx, caseID)
		if err != nil || result == nil {
			c.JSON(http.StatusNotFound, gin.H{"error": "case not found"})
			return
		}
		suspectAddress = result.SuspectAddress
		riskScore = result.RiskScore
		confScore = result.Confidence
	}

	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(190, 10, "D-CRYPT Trace Report", "", 1, "C", false, 0, "")
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(50, 10, "Case ID:", "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(140, 10, caseID, "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(50, 10, "Suspect Address:", "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(140, 10, suspectAddress, "", 1, "L", false, 0, "")

	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(50, 10, "AI Risk Score:", "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(140, 10, strconv.FormatFloat(riskScore, 'f', 1, 64)+"/100", "", 1, "L", false, 0, "")
	
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(50, 10, "Confidence:", "", 0, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(140, 10, strconv.FormatFloat(confScore, 'f', 1, 64)+"%", "", 1, "L", false, 0, "")
	
	pdf.Ln(10)
	pdf.SetFont("Arial", "I", 10)
	pdf.MultiCell(190, 6, "This automated intelligence report was generated by the D-CRYPT tracer. Further visual evidence and timeline analysis can be found on the D-CRYPT investigation dashboard.", "", "L", false)

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", `attachment; filename="Report_`+caseID+`.pdf"`)
	_ = pdf.Output(c.Writer)
}

// GenerateEvidencePackage compiles a comprehensive PDF evidence package.
func (h *Handler) GenerateEvidencePackage(c *gin.Context) {
	h.GenerateReport(c)
}
